### ISSUE TITLE
Support for JunOS | Show System Alarms

### ISSUE THREAD

**Issue by pulsewavelfo** [haussli/rancid#33]
Hi,

Is it possibe to add support for Juniper SRX's to "show system alarms", currently as I can see we only have chassis alarms. This would be helpful because it will show errors such as an IDS Licence expiry? 

`juniper-srx;command;junos::ShowSystemAlarms;show system alarms`

I naively thought I could just add it myself to the configuration but this results in :

`loadtype: undefined function in juniper-srx: junos::ShowSystemAlarms
Couldn't load device type spec for juniper-srx
loadtype: undefined function in juniper-srx: junos::ShowSystemAlarms
Couldn't load device type spec for juniper-srx
loadtype: undefined function in juniper-srx: junos::ShowSystemAlarms
Couldn't load device type spec for juniper-srx
loadtype: undefined function in juniper-srx: junos::ShowSystemAlarms
Couldn't load device type spec for juniper-srx
=====================================`

Thanks for your consideration.

**Comment by haussli** [comment]
I have no SRXs myself.  I presume its no different, so you can try adding

juniper-srx;command;junos::ShowChassisAlarms;show system alarms

**Comment by pulsewavelfo** [comment]
@haussli Am I correct to simply add this to  /etc/rancid.types.conf ? or are additional actions required . I tried previously and it resulted in loadtype: undefined function in juniper-srx in the rancid log.  I wonder if I missed a step , thank you!

**Comment by haussli** [comment]
yes.  seems to work for other flavours.  lmk if not for srx.

https://github.com/haussli/rancid/commit/6042431f10f5cf1dee335c949fd4c5fde79be6a4

**Comment by pulsewavelfo** [comment]
Works thank you very much , except " IDP Signature usage requires a license" keeps being added as a change each time I'm assuming because of time stamp change. Is there a solution so that this is only flagged once until the problem is cleared?

- # 2021-11-15 06:20:09 NZDT Minor  IDP Signature usage requires a license
+ # 2021-11-15 06:25:09 NZDT Minor  IDP Signature usage requires a license
- # 2021-11-15 06:05:09 NZDT Minor  IDP Signature usage requires a license
+ # 2021-11-15 06:10:09 NZDT Minor  IDP Signature usage requires a license

**Comment by haussli** [comment]
https://github.com/haussli/rancid/commit/77e2e895b2f131755f530e24306e563eeebc12cf
